export const translationKeys = {
  resultDownloadBtn: "result_download_btn",
  uploadPageTitle: "upload_page_title",
  tableField: "th_field",
  tableExtracted: "th_extracted",
  tableReviewed: "th_reviewed",
  tableFileName: "td_file_name",
  tableStatus: "td_status",
  tableFileType: "td_file_type",
  tableCaseNumber: "td_case_number",
  tableMasterNameCode: "td_master_name_code",
  tableInvoiceDate: "td_invoice_date",
  tableInvoiceNumber: "td_invoice_number",
  tableAmountBilled: "td_amount_billed",
  alternativeDataTitle: "alternative_data_title",
  pdfToggleOriginalView: "pdf_toggle_original_view",
  fileUpload: "file_upload",

  sidebar: {
    uploadFiles: "sidebar_upload_files",
    uploadBtn: "sidebar_upload_btn",
  },

  filter: {
    companyFilter: "company_filter",
    companyFilterAll: "company_filter_all",
    companyFilterOther: "company_filter_other",
  },
};

export const TRANSLATIONS = {
  en: {
    [translationKeys.filter.companyFilter]: "Unverified Company",
    [translationKeys.filter.companyFilterAll]: "All Companies",
    [translationKeys.filter.companyFilterOther]: "Unverified Company",
    [translationKeys.sidebar.uploadFiles]: "Uploaded File",
    [translationKeys.resultDownloadBtn]: "Download",
    [translationKeys.uploadPageTitle]: "Data Extraction Results",
    [translationKeys.tableField]: "FIELD",
    [translationKeys.tableExtracted]: "EXTRACTED",
    [translationKeys.tableReviewed]: "REVIEWED",
    [translationKeys.tableFileName]: "FILE NAME",
    [translationKeys.tableCaseNumber]: "CASE NUMBER",
    [translationKeys.tableStatus]: "STATUS",
    [translationKeys.tableFileType]: "FILE TYPE",
    [translationKeys.tableMasterNameCode]: "MASTER NAME:CODE",
    [translationKeys.tableInvoiceDate]: "INVOICE DATE",
    [translationKeys.tableInvoiceNumber]: "INVOICE NUMBER",
    [translationKeys.tableAmountBilled]: "AMOUNT BILLED",
    [translationKeys.alternativeDataTitle]: "Alternative Data",
    [translationKeys.sidebar.uploadBtn]: "Upload",
    [translationKeys.pdfToggleOriginalView]: "Original View",
    [translationKeys.fileUpload]: "Upload Files",
  },
  ko: {
    [translationKeys.sidebar.uploadFiles]: "업로드된 파일",
    [translationKeys.filter.companyFilter]: "미확인 회사",
    [translationKeys.filter.companyFilterAll]: "모든 회사",
    [translationKeys.filter.companyFilterOther]: "미확인 회사",
    [translationKeys.resultDownloadBtn]: "다운로드",
    [translationKeys.uploadPageTitle]: "데이터 추출 결과",
    [translationKeys.tableField]: "필드",
    [translationKeys.tableExtracted]: "추출",
    [translationKeys.tableReviewed]: "검토",
    [translationKeys.tableStatus]: "상태",
    [translationKeys.tableFileType]: "파일 유형",
    [translationKeys.tableFileName]: "파일명",
    [translationKeys.tableCaseNumber]: "가안건 번호",
    [translationKeys.tableMasterNameCode]: "마스터명:코드",
    [translationKeys.tableInvoiceDate]: "송장일자",
    [translationKeys.tableInvoiceNumber]: "송장번호",
    [translationKeys.tableAmountBilled]: "송장금액",
    [translationKeys.alternativeDataTitle]: "대체 데이터",
    [translationKeys.sidebar.uploadBtn]: "업로드",
    [translationKeys.pdfToggleOriginalView]: "원본보기",
    [translationKeys.fileUpload]: "파일 업로드",
  },
  ja: {
    [translationKeys.sidebar.uploadFiles]: "アップロードファイル",
    [translationKeys.filter.companyFilter]: "未確認会社",
    [translationKeys.filter.companyFilterAll]: "すべての会社",
    [translationKeys.filter.companyFilterOther]: "未確認会社",
    [translationKeys.resultDownloadBtn]: "ダウンロード",
    [translationKeys.uploadPageTitle]: "データ抽出結果",
    [translationKeys.tableField]: "フィールド",
    [translationKeys.tableExtracted]: "抽出",
    [translationKeys.tableReviewed]: "検証",
    [translationKeys.tableFileName]: "ファイル名",
    [translationKeys.tableCaseNumber]: "仮案件番号",
    [translationKeys.tableMasterNameCode]: "支払先:コード",
    [translationKeys.tableInvoiceDate]: "請求書日付",
    [translationKeys.tableInvoiceNumber]: "請求書番号",
    [translationKeys.tableAmountBilled]: "請求金額",
    [translationKeys.tableStatus]: "ステータス",
    [translationKeys.tableFileType]: "ファイルタイプ",
    [translationKeys.alternativeDataTitle]: "代替データ",
    [translationKeys.sidebar.uploadBtn]: "アップロード",
    [translationKeys.pdfToggleOriginalView]: "原本表示",
    [translationKeys.fileUpload]: "ファイルアップロード",
  },
};
